# Generated by Django 4.1.3 on 2022-11-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='Some discount', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(default='Some Tax', max_length=15),
            preserve_default=False,
        ),
    ]
