# Generated by Django 4.1.3 on 2022-11-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_discount_name_tax_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='stripe_id',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
