# Generated by Django 4.1.3 on 2022-11-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_discount_stripe_id_tax_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.CharField(default='Default description', max_length=50),
        ),
        migrations.AddField(
            model_name='tax',
            name='description',
            field=models.CharField(default='Default description', max_length=50),
        ),
    ]
