# Generated by Django 4.1.3 on 2022-11-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_discount_alter_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='stripe_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='stripe_id',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
